export const FETCH_ARTICLE_DETAILS = 'FETCH_ARTICLE_DETAILS';
export const SET_ARTICLE_DETAILS = 'SET_ARTICLE_DETAILS';

export const SET_LOGIN_DETAILS = 'SET_LOGIN_DETAILS';
export const FETCH_LOADING_DETAILS = 'FETCH_LOADING_DETAILS';

export const API = 'API';
export const API_START = 'API_START';
export const API_END = 'API_END';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const API_ERROR = 'API_ERROR';
